### PR TITLE
perf: Improves performance for big documents

### PR DESCRIPTION
**Pull request by soluchok**
Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

### CODE REVIEW

**Comment by kazarena** [comment]
Thank you, @soluchok. I will review asap. At first glance, all looks good.

I appreciate the effort you've put into it!

**Review by fqutishat — APPROVED** [review]

**Comment by fqutishat** [comment]
@kazarena can we merge PR if it looks good for you. We really need this fix

**Comment by kazarena** [comment]
@fqutishat testing now

**Comment by kazarena** [comment]
All good. Thank you. I'll add @soluchok to the contributors list with the next minor release.

**Pull request merged**
