### PR TITLE
Travis test and testable example

### PR DESCRIPTION
**Pull request by yookoala**
* Add [travis test](https://travis-ci.org/) configuration. CI test for future commits.
* Add badges and links.
* Improve documentation and test coverage by converting example to [testable example](https://blog.golang.org/examples)

### CODE REVIEW

**Comment by kazarena** [comment]
@yookoala many thanks for the PR, it's very useful.

My only concern is about turning examples into tests:

* These examples aren't really tests (they don't test anything)
* They connect to external resources
* There is extensive test coverage for this functionality already

I would either leave them as examples or, if you feel there's a need to have simple tests as a way to learn/play with the library, add asserts and mock out any external connectivity.

**Comment by yookoala** [comment]
Turning examples into testable example would:
1. Improve the Godoc page (see [the doc page of my fork](https://godoc.org/github.com/yookoala/json-gold/ld)). Only examples there would display on the doc page (next to the relevant function / method).
2. With the help of CI setup, ensure that the examples works indeed on every commit. Or, let you know when they no longer work.

If I'm not mistaken, only **ExampleJsonLdProcessor_Expand_online()** links to external resource (thus online). We could improve it by overriding the DocumentLoader.

**Comment by kazarena** [comment]
@yookoala in regards to the examples, this is very smart!

New commits also make a lot of sense. Will merge soon.

**Comment by yookoala** [comment]
@kazarena: To make the travis setup really work, you'd need to:
1. Login to [Travis](https://travis-ci.org/) with your Github account.
2. Allow Travis to read this repository / Synchronize your account with it.
3. Enable tests for this repository.

Then newer comment / pull requests will trigger Travis CI testing and report to Github.

**Comment by kazarena** [comment]
@yookoala This is done and the build is passing. Thank you!

**Pull request merged**
